name: Manual workflow

on:
  discussion_comment:
    types: [created]

jobs:
  notify_discussion_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Escape body
      id: escape-body
      run: |
        BODY="${{ github.event.comment.body }}"
        BODY="${BODY//'"'/'\"'}"
        BODY="${BODY//'\n'/'%0A'}"
        BODY="${BODY//'\r'/'%0D'}"
        echo "::set-output name=body::${BODY}"
    - name: Send message
      env:
        PAYLOAD: |
            {
              "attachments": [
                {
                  "pretext": "New discussion comment created by ${{ github.event.comment.user.login }}",
                  "author_name": "${{ github.event.comment.user.login }}",
                  "author_link": "${{ github.event.comment.user.html_url }}",
                  "author_icon": "${{ github.event.comment.user.avatar_url }}",
                  "title": "Comment on ${{ github.event.discussion.title }}",
                  "title_link": "${{ github.event.comment.html_url }}",
                  "text": "${{ steps.escape-body.outputs.body }}"
                }
              ]
            }
      run: |
        curl \
          -X POST \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          ${{ secrets.SLACK_DISCUSSION_CHANNEL_WEBHOOK_URL }}
