name: Manual workflow

on:
  discussion_comment:
    types: [created]

jobs:
  notify_discussion_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare for notify
      id: slack-prepare
      run: |
          DISCUSSION_COMMENT=$(cat << EOF
          ${{ github.event.comment.body }}
          EOF
          )
          DISCUSSION_COMMENT="${DISCUSSION_COMMENT//$'\n'/'\\n'}"
          DISCUSSION_COMMENT="${DISCUSSION_COMMENT//$'\r'/''}"
          echo -E "::set-output name=discussion-comment::${DISCUSSION_COMMENT}"
    - uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "attachments": [
              {
                "mrkdwn_in": ["text"],
                "pretext": "New discussion comment created by ${{ github.event.comment.user.login }}",
                "author_name": "${{ github.event.comment.user.login }}",
                "author_link": "${{ github.event.comment.user.html_url }}",
                "author_icon": "${{ github.event.comment.user.avatar_url }}",
                "title": "Comment on ${{ github.event.discussion.title }}",
                "title_link": "${{ github.event.comment.html_url }}",
                "text": "${{ steps.slack-prepare.outputs.discussion-comment }}"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DISCUSSION_CHANNEL_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
